### ISSUE TITLE
activity_logs_list has stopped working

### ISSUE THREAD

**Issue by iHiD** [zokioki/fitbit_api#12]
Hello. Thanks for this Gem. I've used it in production for many years and it's been great.

In the last few weeks, we ran into an issue with [`activity_logs_list`](https://github.com/zokioki/fitbit_api/blob/809fdcfa081a5b597400880d15a5e157c44d9b12/lib/fitbit_api/activities.rb#L63).

It seems that FitBit's API will now break if an empty `afterDate` is passed in with a `beforeDate`. I am presuming that before FitBit silently ignored an empty `afterDate` but now it raises a 400 with a bad argument. 

I think the solution is to just strip empty args when making API calls. But I'm not sure enough of how you'd want to solve this to make a PR. I figure it's easier for you to do.

I've monkeypatched the method locally to just not have `afterDate` as a default param and things now work again for my usecase.

Thanks!

**Comment by zokioki** [comment]
Thanks for raising this issue @iHiD, I'll see if I can carve out some time this week to address it. Will ping back with any updates.
