### ISSUE TITLE
Unable to call method client.activity_time_series

### ISSUE THREAD

**Issue by prashantham** [zokioki/fitbit_api#3]
If i call the method with below params

client.activity_time_series('tracker/steps', {end_date: Date.today, period: "max"})
client.activity_time_series('tracker/steps', end_date: Date.today.iso8601, period: "1d")

i get ArgumentError (unknown keywords: end_date, period)

But if i do 
client.activity_time_series('tracker/steps', end_date: Date.today.iso8601, period: "x")

i get FitbitAPI::InvalidArgumentError (Invalid period: "x". Please provide one of the following: ["1d", "7d", "30d", "1w", "1m", "3m", "6m", "1y", "max"].)

I am using ruby 2.5.1

**Comment by zokioki** [comment]
Hi @prashantham - thanks for the bug report! 

This was a bug introduced in `v0.8.2`, affecting GET requests. I've pushed up a fix via https://github.com/zokioki/fitbit_api/commit/7396c395ddcf8bd4a7062d19e833f380a8e5b2d4 and have released [**`v0.8.3`**](https://github.com/zokioki/fitbit_api/releases/tag/v0.8.3) - if you pull that version down, `#activity_time_series` should now work 👍

**Comment by zokioki** [comment]
Hi @prashantham - thanks for the bug report!

This was a bug introduced in `v0.8.2`, affecting GET requests. I've pushed up a fix via 7396c39 and have released [`v0.8.3`](https://github.com/zokioki/fitbit_api/releases/tag/v0.8.3) - if you pull that version down, `#activity_time_series` should now work.
