### ISSUE TITLE
undefined method 'expired?' for nil:NilClass

### ISSUE THREAD

**Issue by iamdriz** [zokioki/fitbit_api#4]
In my callback method I have the following:
~~~
@client.get_token(params[:code])
redirect_to dashboard_path
~~~

And then on the Dashboard I have:
~~~
@devices = @client.devices
~~~

However it returns the error: `undefined method 'expired?' for nil:NilClass`

Looking into your gem code it looks like because the `@token` is `nil` it's what's causing the error when it's trying to check if it's expired. Because it hasn't been set.

However when debugging I am in fact getting a correct return from Fitbit so the tokens, etc are all being returned so that instance variable should of been set. I vendorized the gem and tried to debug it using Visual Studio code like so:

![image](https://user-images.githubusercontent.com/801252/42665185-61e410c6-8636-11e8-8edf-05a74a2aaa29.png)

And what I'm finding is that `@token` is being set fine. But when it hits the second breakpoint it's `nil` causing the issue. Why is the instance variable losing the data?

**Comment by iamdriz** [comment]
I understand why this breaks now. This is actually a bit of a flaw in this Gem.

Normally when you get a token you retain it and then make requests using it as a header/param and then request a new one if it's ever expired. However because you are storing the token against the instance: https://github.com/zokioki/fitbit_api/blob/master/lib/fitbit_api/client.rb#L51 it means that the token is not usable after that point.

In your Rails example you are getting around this by creating a new instance of the class in the user model and passing a new refresh token on each request. So this Gem only seems to work in that scenario. The only way I can see around it, would be to store the token and then bypass the gem and make manual requests using the token instead of relying on the instance.

**Comment by zokioki** [comment]
Hi Cameron,

Thanks for reporting the issue. That's definitely a gap in the current implementation of the gem; I'll try to find some time to sit down over the weekend to take a look at it.

**Comment by iamdriz** [comment]
@zokioki Excellent thanks. Look forward to seeing what you come up with!

**Comment by zokioki** [comment]
@iamdriz the option to pass an access token has been added to [v0.9.0](https://github.com/zokioki/fitbit_api/releases/tag/v0.9.0) of the gem.

If you already have the user's token data stored (along with their Fitbit user_id), you'll now be able to instantiate a client object like so:

```ruby
client = FitbitAPI::Client.new(
  client_id: 'xxx', 
  client_secret: 'xxx', 
  access_token: 'xxx', 
  refresh_token: 'xxx',
  expires_at: 'xxx',
  user_id: 'xxx'
)
```

The example Rails app has been updated to reflect these changes as well. 

Let me know if this helps!

**Comment by iamdriz** [comment]
How does this line work: https://github.com/zokioki/fitbit_api_rails/blob/master/app/models/user.rb#L35
If you are creating a new instance of the class... how does it know what the client id and secret is?

**Comment by zokioki** [comment]
The new token is requested internally from the client when it expires:

https://github.com/zokioki/fitbit_api/blob/13c8cf99fbab2327e3429d590a71ccfc4b633045/lib/fitbit_api/client.rb#L41-L43

It's at this point that the callback updates the Identity record, with the new `access_token`, `refresh_token` and `expires_at` values. Otherwise the callback skips the update to the record as none of those values have been changed.

**Comment by zokioki** [comment]
You're able to set some default options for the gem to inherit from, via an initializer:

https://github.com/zokioki/fitbit_api_rails/blob/dd3b53dee9a9b317f882000760ed08bf238029b3/config/initializers/fitbit_api.rb

Just added a section for it in the [README](https://github.com/zokioki/fitbit_api#options) with the release of `v0.9.0`.
