### ISSUE TITLE
Persistent storage for access and refresh tokens

### ISSUE THREAD

**Issue by harry-m** [zokioki/fitbit_api#9]
Hello,

Many thanks for your work on this gem - it's been very easy to use! I'm just having one problem.

I'm using the gem in a command-line application, and currently, I am having to go through the oauth authentication again quite frequently - at least daily.

I think this is because the original tokens are expiring and I'm not using the most recent tokens for subsequent runs, as they are not currently stored persistently.

Unfortunately I can't see an easy way to do this - have I missed something? Is there a way to have the gem call back or something so that I can store new access and refresh tokens for subsequent runs?

Cheers!

**Comment by zokioki** [comment]
Hello,

Thanks for opening the issue. I have pushed up a new release ([v0.10.0](https://github.com/zokioki/fitbit_api/releases/tag/v0.10.0)) that should make handling token refreshes more flexible. You can now specify an optional callback method that is executed whenever the token is refreshed, e.g.:

```ruby
client = FitbitAPI::Client.new(...)
client.on_token_refresh = ->(token) { puts "Token refreshed: #{token.refresh_token}" }
```

The client instance will [try to refresh](https://github.com/zokioki/fitbit_api/blob/bcdc4912666e91914dbf643e2416f452311d04a4/lib/fitbit_api/client.rb#L124) the token before making a request if the token has expired. If you need more granular control of how token refreshes are handled you can now disable this auto-refresh behavior and trigger the refresh manually:

```ruby
client.auto_refresh_token = false
client.refresh_token!

#=> Token refreshed: RjY2NjM5NzA2OWJjuE7c
```

Hope this is helpful!
